# Generated by Django 4.2.3 on 2023-08-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='new_email',
        ),
    ]
