# Generated by Django 4.2.3 on 2023-08-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackmodel',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
