# Generated by Django 4.2.3 on 2023-08-08 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproductmodel',
            name='product_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
